project:
  type: website
  output-dir: docs

website:
  title: "Large Language Model tools for R"
  navbar:
    background: "#01497c"
    pinned: true
    align: left
    left: 
      - href: index.qmd
        text: Home
      - href: course.qmd
        text: Outline and schedule
      - href: materials.qmd
        text: Course materials
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)."
    right: "Luis D. Verde Arregoitia - 2025"

format:
  html:
    theme: 
      light: [flatly, web_styles.scss]
    toc: true
    mainfont: "Inclusive Sans"
    
execute:
  freeze: auto
